apiVersion: v2
name: rtsp-to-hls
description: Convert RTSP to HLS stream
type: application

version: 0.1.2
appVersion: "0.0.1"

dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
