image:
  repository: ghcr.io/vhdirk/rtsp-to-hls
  pullPolicy: Always
  tag: single-stream

securityContext:
  privileged: false

service:
  main:
    ports:
      http:
        port: 8083

config: "{}"
