image:
  repository: ghcr.io/vhdirk/rtsp-to-hls
  pullPolicy: Always
  tag: single-stream

imagePullSecrets:
  - name: dockerconfigjson-github-com

securityContext:
  privileged: false

service:
  main:
    ports:
      http:
        port: 8083