title: "@vhdirk"

remote_theme: vhdirk/rigr-jekyll

# About/contact
author:
  name:              Dirk Van Haerenborgh
  url:               https://vhdirk.github.io
  email:             vhdirk@gmail.com

use_cdn: true

theme_variant: "toggle"

analytics:
  enabled: true
  umami:
    host_url: https://eu.umami.is
    website_id: "dbe0c112-4562-4413-b328-fe94884d92f3"

menu:
  - name: /posts
    url: /posts
    weight: 1
  - name: /projects
    url: /projects
    weight: 2
  - name: /about
    url: /about
    weight: 3


socials:
  - name: github
    url: "https://github.com/vhdirk/"
    icon: github
