apiVersion: v2
name: genie
description: The home server version of Almond
type: application

version: 0.1.2
appVersion: "3.0.1"

dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
