---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gazette.name" . }}-config
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    app: {{ include "gazette.name" . }}
    chart: {{ include "gazette.chart" . }}
data:
  config.json: |
{{ .Values.config | indent 4 }}