---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gazette-config.name" . }}-config
  labels:
    app: {{ include "gazette-config.name" . }}
    chart: {{ include "gazette-config.chart" . }}
data:
  config.json: |
{{ .Values.config | indent 4 }}