image:
  repository: ghcr.io/ajnart/homarr
  pullPolicy: Always
  tag: latest

service:
  main:
    ports:
      http:
        port: 7575

ingress:
  main:
    enabled: false

persistence:
  config:
    enabled: false
    mountPath: /app/data/configs
  data:
    enabled: false
    mountPath: /data
  icons:
    enabled: false
    mountPath: /app/public/icons
