image:
  repository: ghcr.io/ajnart/homarr
  pullPolicy: Always
  tag: latest

service:
  main:
    ports:
      http:
        port: 7575

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false
    mountPath: /app/data/configs
  data:
    enabled: false
    mountPath: /data
  icons:
    enabled: false
    mountPath: /app/public/icons
