apiVersion: v2
name: gazette
description: Fetch newspapers in PDF
type: application

version: 0.1.4
appVersion: "0.0.1"

maintainers:
  - email: vhdirk@gmail.com
    name: vhdirk
    url: https://vhdirk.github.io
