apiVersion: v2
name: ubooquity
description: Ubooquity is a free, lightweight and easy-to-use home server for your
  comics and ebooks. Use it to access your files from anywhere, with a tablet, an
  e-reader, a phone or a computer.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.1
appVersion: 2.1.2

dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2