---
{{- include "common.values.setup" . }}

{{/* Append the hardcoded settings */}}
{{- define "rtsp-to-hls.harcodedValues" -}}
persistence:
  config:
    enabled: "true"
    mountPath: "/app/config.json"
    subPath: "config.json"
    type: "custom"
    volumeSpec:
      configMap:
        name: {{ printf "%v-config" (include "common.names.fullname" .) }}

{{- end -}}
{{- $_ := mergeOverwrite .Values (include "rtsp-to-hls.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "common.all" . }}