apiVersion: v2
name: scrutiny
description: Scrutiny WebUI for smartd S.M.A.R.T monitoring. Scrutiny is a Hard Drive Health Dashboard & Monitoring solution.

type: application

version: 0.1.3
appVersion: 2.1.2

maintainers:
  - email: vhdirk@gmail.com
    name: vhdirk
    url: https://vhdirk.github.io

dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
