image:
  repository: ghcr.io/analogj/scrutiny
  pullPolicy: Always
  tag: master-omnibus

env:
  TZ: "UTC"
  PUID: "1000"
  PGID: "1000"

  SCRUTINY_API_ENDPOINT: http://localhost:8080

securityContext:
  privileged: true

service:
  main:
    ports:
      http:
        port: 8080

ingress:
  main:
    enabled: false

persistence:
  varrun:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
  config:
    enabled: true
    mountpath: /opt/scrutiny
  influxdb:
    enabled: true
    mountPath: "/opt/scrutiny/influxdb"
    accessMode: ReadWriteOnce
    size: 3Gi
  udev:
    enabled: true
    type: hostPath
    hostPath: "/run/udev"
    mountPath: "/run/udev"
    readOnly: true

portal:
  open:
    enabled: true
