name: Renovate
on:
  # running every hour from 9h to 19h UTC on every working day
  schedule:
    - cron: "0 9-19 * * 1-5"
  # allow to manually trigger this workflow
  workflow_dispatch:
    inputs:
      renovate_log_level_debug:
        type: boolean
        default: true
  push:
    branches:
      - main
    paths:
      - ".github/renovate.json5"
      - ".github/workflows/renovate.yml"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v40.1.4
        with:
          configurationFile: .github/renovate.json5
          token: "${{ secrets.RENOVATE_TOKEN }}"
        env:
          RENOVATE_ALLOW_POST_UPGRADE_COMMAND_TEMPLATING: true
          RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS: "[^bash ]"
