name: Renovate
on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v40.1.4
        env:
          RENOVATE_TOKEN: "${{ secrets.RENOVATE_TOKEN }}"
